[build]
  command = "NODE_ENV=development npm install && npm run build"
  publish = "dist/ukei-website/browser"
  node_version = "20"
  
[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[[redirects]]
  from = "https://ukeiweb.netlify.app/uploads/*"
  to = "https://ukei-strapi.onrender.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://ukeiweb.netlify.app/api/*"
  to = "https://ukei-strapi.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
