[build]
  command = "NODE_ENV=development npm install && npm run build"
  publish = "dist/ukei-website/browser"
  node_version = "20"
  
[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"