[build]
  # Comando para construir tu proyecto
  command = "npm install && npm run build"
  
  # Carpeta que Netlify usará como public
  publish = "dist/ukei-website/browser"

  # Node.js version compatible con better-sqlite3
  node_version = "20"

[context.production.environment]
  NODE_ENV = "production"